version: '3.3'

services:
  mysql:
    image: mysql:5
    restart: always
    ports:
     - 3306:3306
    volumes: 
     - "./mysql:/var/lib/mysql"
     - "./config/mysql/conf.d:/etc/mysql/conf.d"
    environment: 
     TZ: Asia/Taipei
    
  nginx:
    image: nginx:latest
    restart: always
    ports:
     - 80:80
     - 443:443
    volumes: 
     - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
     - "./log/nginx:/var/log/nginx"
     - "./config/nginx/conf.d:/etc/nginx/conf.d" 
     - "./certbot/conf:/etc/letsencrypt" # Save Certifaction
     - "./certbot/www:/var/www/certbot" # Save Let's encrypt acme challenge 
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports: 
      - 8080:80
    environment: 
      - PMA_HOST=mysql

  certbot:
    image: certbot/certbot
    volumes:
      - "./certbot/conf:/etc/letsencrypt" # Save Certifaction
      - "./certbot/db:/var/lib/letsencrypt"
      - "./certbot/logs:/var/log/letsencrypt"
      - "./certbot/www:/var/www/certbot"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
